### ISSUE TITLE
Local Costmap Inflation doesn't work?

### ISSUE THREAD

**Issue by willdzeng** [ros-planning/navigation#488]
![screenshot from 2016-06-25 16 29 24](https://cloud.githubusercontent.com/assets/12994633/16359671/75657a54-3af2-11e6-929b-b9feba922f78.png)
![screenshot from 2016-06-25 16 29 35](https://cloud.githubusercontent.com/assets/12994633/16359672/7566b8a6-3af2-11e6-9660-ad60eb3fe96a.png)

Because I found out the Inflation of local costmap doesn't work.
I try to visualize the obstacle cost cloud, and found out the Inflation of costmap and the Inflation of obstacle cloud is not the same. 
I am wondering if this is a bug, or it's just the implementation of the map_viz?

**Comment by spmaniato** [comment]
@willdzeng Which distro and which version (release) are you running? I think what you're seeing might be related to #485, which was fixed for Indigo (in #486) two days ago.

**Comment by willdzeng** [comment]
I am using the latest jade-devel, I think that commit is not merged into jade

**Comment by willdzeng** [comment]
Also I found out the local costmap didn't update after the obstacle are removed even after I used the coomit in #486 . 
For example, in the following screenshots.
The point cloud showed that the obstacle is removed, but the local costmap didn't update.
![screenshot from 2016-06-26 14 39 16](https://cloud.githubusercontent.com/assets/12994633/16365178/2f98f102-3bad-11e6-92a7-19c4a0d09603.png)
![screenshot from 2016-06-26 14 39 22](https://cloud.githubusercontent.com/assets/12994633/16365179/2faaac94-3bad-11e6-9550-1ae350bfce04.png)

Here is the parameters I use:

```
obstacle_layer:
  # The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters. This can be over-ridden on a per-sensor basis.
  obstacle_range: 10
  # The default range in meters at which to raytrace out obstacles from the map using sensor data. This can be over-ridden on a per-sensor basis.
  raytrace_range: 10
  max_obstacle_height: 20
  track_unknown_space: true
  clearing: true

  observation_sources: laser_scan_sensor point_cloud_sensorA point_cloud_sensorB

  laser_scan_sensor: {
    data_type: LaserScan,
    topic: scan,
    expected_update_rate: 0.1,
    marking: true,
    clearing: true
  }

  point_cloud_sensorA: {
    sensor_frame: base_link,
    data_type: PointCloud2,
    topic: obstacles_cloud,
    expected_update_rate: 0.5,
    marking: true,
    clearing: true,
    min_obstacle_height: -9999.0,
    max_obstacle_height: 9999,
    observation_persistence: 5
  }

  point_cloud_sensorB: {
    sensor_frame: base_link,
    data_type: PointCloud2,
    topic: ground_cloud,
    expected_update_rate: 0.5,
    marking: false,
    clearing: true,
    min_obstacle_height: -1.0 # make sure the ground is not filtered
  }
```

How do I update the local costmap after the point cloud updated? like ray-trace without seeing obstacle.

**Comment by willdzeng** [comment]
Inflation still doesn't show in the obstacle cost point cloud visualization. This is using the latest indigo-devel branch 

![screenshot from 2016-06-26 15 33 38](https://cloud.githubusercontent.com/assets/12994633/16365388/71def5b0-3bb3-11e6-8fbe-62405d1a8f59.png)
![screenshot from 2016-06-26 15 33 44](https://cloud.githubusercontent.com/assets/12994633/16365387/71df0ff0-3bb3-11e6-9153-1624a924e132.png)

**Comment by mikeferguson** [comment]
I think you are seeing several different things here:
- On the initial post about the point_cloud vs the costmap -- I'm pretty sure that if the costmap is up to date, it will be properly taken into account in the planner -- for instance, the robot radius appears to be all "very high cost". However, depending on the settings you have for the planner costs, the actual cost may drop off quite steeply in the lower cost inflation region (this is pretty commonly done to avoid robots having difficult times in narrow aisles) -- I'm going to close this part of the ticket because I don't think it is actually a bug without further information.
- On the "not clearing" -- you just don't have any data to clear with -- it looks like you are using something like a primesense sensor, and the sensor has very few returned data points in the center region of the camera, probably because the sensor can't see far enough to actually see anything. Lack of data does not cause clearing -- you need actual clearing endpoints to raytrace and actually clear out the previous observations. With short-range sensors this can be quite difficult -- and I've seen many people actually create a second point cloud where all nans/infs/etc are made into "max_range-epsilon" so that lack of data actually does clear -- however, it should be noted that this is not without its own caveats. In the future, this sort of "how do I do X?" really belongs on ROS answers, not in a ticket.

**Comment by willdzeng** [comment]
OK~, I got you. Sorry, I thought it was a bug of the map_viz or inflation didn't take into account. I will try change the cost_scaling_factor to see if it changes.

**Comment by mikeferguson** [comment]
No problem -- especially on that map_viz part, I could see that looking like a bug at first.

One other thought -- you can probably change the scale of min/max in your RVIZ settings, there is probably a very shallow slope across the red region, but the scaling is probably so small compared to the other color differences that it all shows up red.
