### ISSUE TITLE
fake_localization: Param delta_yaw, change in the behaviour

### ISSUE THREAD

**Issue by JavierLRH** [ros-planning/navigation#805]
Hi everyone.

There is a change in the behaviour of the parameter delta_yaw in the last update.
![fake_yaw](https://user-images.githubusercontent.com/39495812/47307109-7be14280-d62e-11e8-8411-dc0ec6c7f0a5.png)

In the old version the tf between map and odom looks like this:
This version works nice
![tf_javi](https://user-images.githubusercontent.com/39495812/47307187-b1862b80-d62e-11e8-804c-d24f1fcd0f06.png)

In the new version the tf between map and odom looks like this:
![tf](https://user-images.githubusercontent.com/39495812/47307287-fa3de480-d62e-11e8-9684-68ebe338b0a0.png)

Thanks.

**Comment by mikeferguson** [comment]
Almost certainly, this is the same bug as fixed in other places here: https://github.com/ros-planning/navigation/pull/762 -- the setEuler function is the wrong one, needs to use setRPY.

**Comment by JavierLRH** [comment]
Ok thanks.

**Comment by JavierLRH** [comment]
Thank you very much! @DLu

**Comment by corot** [comment]
This seems to be the underlying problem: https://github.com/ros/geometry2/issues/190

Replacing with setRPY fixes this package, but the library still wrong, ready to plague other progects
